root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ./cmd/api"
  bin = "tmp/app"

  include_ext = ["go", "toml", "yaml"]
  exclude_dir = ["tmp", "vendor", "node_modules", ".git"]

[log]
  time = true